%% PBRT integrands
tic; 
clear ;
s(1) = GenSamplStruct('Jittered', '') ;
s(2) = GenSamplStruct('Random', '') ;

legend = 'chair';
i(1) = GenIntegStruct('Pbrt', ...
            [ '--epath /home/kartic/pbrt/pbrt-v3/pbrt ' ...
            '--spath /home/kartic/pbrt/pbrt-v3-scenes/breakfast/breakfast-crop.pbrt '...
            '--pypath /home/kartic/Projects/FAS2016/code/Analysis/python/pbrt-cl.py '...
            '--crop 0.335 0.36 0.688 0.7 --pbrtstype $$SAMP$$ --refnspp 0 --img pbrt-eea.exr'], ...
            legend ) ;

legend = 'bunny' ;
i(2) = GenIntegStruct('Pbrt', ...
            [ '--epath /home/kartic/pbrt/pbrt-v3/pbrt ' ...
            '--spath /home/kartic/pbrt/pbrt-v3-scenes/breakfast/breakfast-crop.pbrt '...
            '--pypath /home/kartic/Projects/FAS2016/code/Analysis/python/pbrt-cl.py '...
            '--crop 0.445 0.465 0.48 0.51 --pbrtstype $$SAMP$$ --refnspp 0 --img pbrt-eea.exr'], ...
            legend ) ;

legend = 'floor' ;
i(3) = GenIntegStruct('Pbrt', ...
            [ '--epath /home/kartic/pbrt/pbrt-v3/pbrt ' ...
            '--spath /home/kartic/pbrt/pbrt-v3-scenes/breakfast/breakfast-crop.pbrt '...
            '--pypath /home/kartic/Projects/FAS2016/code/Analysis/python/pbrt-cl.py '...
            '--crop 0.168 0.2 0.89 0.91 --pbrtstype $$SAMP$$ --refnspp 0 --img pbrt-eea.exr'], ...
            legend ) ;

        
ns = [4 16 64 100] ;
nr =  30;
ofile = '../out/test';
binfile = '../build/eea' ;
atype = 'var' ;

system (['rm ' ofile '*.txt']) ;
data = CollectConvData(ns, nr, ofile, binfile, s, i, atype) ;
toc
%% Plot data generated by CollectConvData

PlotConvData(data) ;


%% Other integrands

clear; 
%%%%%%%%%%% samplers 
s(1) = GenSamplStruct('Jittered', '') ;
s(2) = GenSamplStruct('Random', '') ;
s(3) = GenSamplStruct('BJittered', '--boxwidth .3') ;
s(4) = GenSamplStruct('BJittered', '--boxwidth .5') ;
s(5) = GenSamplStruct('GJittered', '--sigma .3') ;
s(6) = GenSamplStruct('GJittered', '--sigma .5') ;

%%%%%%%%%%% Integrands
i(1) = GenIntegStruct('QuadPix', ['--points ' num2str(rand(1,4))]) ;
i(2) = GenIntegStruct('PWConstant', '--npts 100 --random') ;
% i(3) = GenIntegStruct('Gaussian', '--center .5 .5 --sigma .2 .4') ;
i(3) = GenIntegStruct('Disk', '--center .5 .5 --rad .3') ;


%%%%%%%%%%% Analysis Parameters
ns = [9 36 100 1024 4096] ;
nr =  250;
ofile = '../out/test';
binfile = '../build/eea' ;
atype = 'mse' ;

system (['rm ' ofile '*.txt']) ;
tic
data = CollectConvData(ns, nr, ofile, binfile, s, i, atype) ;
toc

%% Plot data generated by CollectConvData

PlotConvData(data) ;



